/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SlingCoinERC20 } from "./SlingCoinERC20";
export type { WillowCoinERC20 } from "./WillowCoinERC20";
